### ISSUE TITLE
LinkLayer causes timeout waiting for an ack to an ack

### ISSUE THREAD

**Issue by ferm10n** [netsmarttech/node-open-protocol#10]
My team encountered this problem a few months ago while working with a PowerMACS 4000, which didn't support acknowledgement via sequence numbers. I've been meaning to get around to opening issues for the things we found and push up my changes!

Why the timeout happens:
* `SessionControlClient.useLinkLayer` is false
* A data MID is received, such as 0106
* Because `useLinkLayer` is false, the appropriate ack MID is returned (0108)
* Whenever LinkLayer sends a MID in `_onDataMidSerializer()`, it normally sets a timeout UNLESS the mid being sent is a `POSITIVE_ACK` or `NEGATIVE_ACK`
* The timeout is set so the MID can be resent, if it is not acknowledged
* However, an ack MID like 0108 is passed to `_onDataMidSerializer`, the timer for `_resentMid` is set
* Heartbeat messages keeping the connection alive are not able to be sent, because the `LinkLayer` is stuck waiting for an ack to an ack, and the connection dies

node version: v10.15.1
node-open-protocol version: 1.0.3

**Comment by gfcittolin** [comment]
Hey @ferm10n 

Thanks for all the issues and PRs, we really appreciate it! We're currently quite busy on another project, so that's why we still haven't touched them, but in the next few days somebody from our team will take a look on it.
