### ISSUE TITLE
fs library issue 

### ISSUE THREAD

**Issue by Babygalla123** [netsmarttech/node-open-protocol#20]
Hi... 
Thanks for the great library . i had tried this in node js. 
It is working fine.
But my main intention is i want to use this library in react native. since i am developing mobile application in react native.
I could able to add the library to react native project using ''npm'', and i am able to see in  'package.json' file  under dependencies.

"dependencies": {
    "node-open-protocol": "^1.1.1",
    "react": "16.11.0",
    "react-native": "0.62.2"} 

After spending so much of time in this final i could able to run this library. But there is small issue now. from "fs" library it's throwing, few methods it's not able to find . 
here i am attaching the error. Kindly help me on this. 
![Screenshot_20200709-161215](https://user-images.githubusercontent.com/35566498/87117964-a1493080-c297-11ea-8075-458bcdf584ce.png)

Thanks in advance!!

**Comment by gfcittolin** [comment]
This is related to this library being used with react native, therefore I'm closing this here so we can follow-up everything on #19
