### ISSUE TITLE
Desoutter connection

### ISSUE THREAD

**Issue by Batistleman** [netsmarttech/node-open-protocol#5]
I'm trying to make a connection with a Desoutter tool, but I get this error:

```
Error: [Session Control Client] [Connect] negative acknowledge, MID[1], Error [Command failed]
    at receivedReply (/open-protocol-tests/node_modules/node-open-protocol/src/sessionControlClient.js:321:29)
    at LinkLayer.ll.on (/open-protocol-tests/node_modules/node-open-protocol/src/sessionControlClient.js:400:38)
    at emitOne (events.js:115:13)
    at LinkLayer.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at LinkLayer.Readable.push (_stream_readable.js:208:10)
    at LinkLayer._onDataMidParser (/open-protocol-tests/node_modules/node-open-protocol/src/linkLayer.js:324:19)
    at MIDParser.LinkLayer.midParser.on (/open-protocol-tests/node_modules/node-open-protocol/src/linkLayer.js:106:50)
    at emitOne (events.js:115:13)
```

I have this simple code running:

```
let op = openProtocol.createClient(port, ip, (data) => {
    console.log(data);
});
```

On the controller itself there is a message:
'Open Protocol lost connection TU1'

Any ideas? How can we help debug this?

**Comment by DiegoRampim** [comment]
In this case, you received a MID 0004 (Negative ACK) with error code `79 (Command failed)`, but on Open Protocol's manual this code is a generic error code and has no specific meaning.
I guess, it must be related with MID Revision.
Please try the following code:

```javascript
const openProtocol = require('node-open-protocol');

let controllerIp = "127.0.0.1";
let controllerPort = "4545";

let opts = {
    "defaultRevisions": {
        "1": 1
    }
};

let op = openProtocol.createClient(controllerPort, controllerIp, opts, (data) => {
    // data is the content of MID 0002
    console.log("Connected");
    console.log("MID 0002", data);
});
```

Quick question: What is your controller's model?

**Comment by Batistleman** [comment]
Great, thanks! That seems to work. I guess this means the controller is only accepting Open Protocol revision 1 commands?

The controller data I get back:

```
{
    mid: 2,
    revision: 1,
    noAck: false,
    stationID: 1,
    spindleID: 1,
    sequenceNumber: 0,
    messageParts: 0,
    messageNumber: 0,
    payload: {
        cellID: 0, 
        channelID: 1, 
        controllerName: 'CVI3 Vision'
    }
}
```

**Comment by machadotiago** [comment]
Hello @Batistleman  
great that it worked!
The library should actually negotiate the revision with the controller. The protocol says that we can start a communication with the highest implemented revision and, if the controller does not support it, it should inform the Master in order to try a lower revision. This seems to not work in your environment for some unknown reason.
Maybe you can try another revision (we have implemented revision from 1 to 6) to see which one is working and which one is not working.

Question: are you working with a CVI3  Vision? If yes, can you send us the firmware version?
That would be great for our documentation.

and, by the way, can you tell us what is your application for this node?

**Comment by Batistleman** [comment]
I can go up to revision 4. The controller data I get back:

```
{
    mid: 2,
    revision: 4,
    noAck: false,
    stationID: 1,
    spindleID: 1,
    sequenceNumber: 0,
    messageParts: 0,
    messageNumber: 0,
    payload:
        {
            cellID: 0,
            channelID: 1,
            controllerName: 'CVI3 Vision',
            supplierCode: 'DE3',
            openProtocolVersion: 'v1.0',
            controllerSoftwareVersion: '1.5.2.0',
            toolSoftwareVersion: '',
            rbuType: '',
            controllerSerialNumber: 'xxxxxxxxxxxx'
        }
}
```

So I guess the firmware version is 1.5.2.0?

Our application: We have a system for managing work instructions and want to select a certain torque value coupled to an instruction step. (Our software is https://azumuta.com)

**Comment by Batistleman** [comment]
FYI, we're adding some response parsing (101) here: https://github.com/Azumuta/node-open-protocol
We'll make a pull request once we did some tests.

**Comment by machadotiago** [comment]
Hello @Batistleman,
thanks, we would be glad to accept your PR with this new MID implementation.

**Comment by vinothitian** [comment]
Hi,

We are trying to connect Desoutter tool through the below code, we are able to get the response for first time, then after some time, we are getting message like "Service Unavailable"

const openProtocol = global.get('nodeOpenProtocolDesoutter')
 //nodeOpenProtocolDesoutter;
let options = { // Weather to use LinkLayer Acknowledgement
//true: enforce activation
//false: enforce deactivation
//undefined: auto negotiate
linkLayerActivate: undefined, // Weather to user Generic MID request/subscription
//true: use generics
//false or undefined: don't use generics
genericMode: undefined,
[19:20] Darshan S (IT/Hosur/TVSMotor)
const openProtocol = global.get('nodeOpenProtocolDesoutter') //nodeOpenProtocolDesoutter;let options = { // Weather to use LinkLayer Acknowledgement
//true: enforce activation
//false: enforce deactivation
//undefined: auto negotiate
linkLayerActivate: undefined, // Weather to user Generic MID request/subscription
//true: use generics
//false or undefined: don't use generics
genericMode: undefined,
keepAlive: 10000, // Weather the library will append a parameter "_raw" with the Buffer as received from the controller
rawData: false, // How long we'll wait for an acknowledge of the controller to a message that we send, in milliseconds
timeOut: 3000, // How many times we'll retry to send a message if we don't receive an answer
retryTimes: 3, // A list of MIDs for which we'll not parse the payload
disableMidParsing: {}
}try{
let op = openProtocol.createClient(4545, '10.131.162.80', options, (err) => {
if(err){
msg.payload = "Error on client creation: "+err;
node.send(err);
}
});
global.set('dummyToolClient', op);
op.on('error',(err)=>{
msg.payload = err.toString();
node.send(msg);
})
op.on('connect',(data)=>{
msg.payload = data;
node.send(msg);
})
op.on("close",(data)=>{
msg.payload = data.toString();
node.send(msg);
})
}
catch(error){
msg.payload = error.toString();
node.send(msg);
}return msg;

revision:2, // How oft we send keep-alive messages (MID 9999), in milliseconds
keepAlive: 10000, // Weather the library will append a parameter "_raw" with the Buffer as received from the controller
rawData: false, // How long we'll wait for an acknowledge of the controller to a message that we send, in milliseconds
timeOut: 3000, // How many times we'll retry to send a message if we don't receive an answer
retryTimes: 3, // A list of MIDs for which we'll not parse the payload
disableMidParsing: {}
}try{
let op = openProtocol.createClient(4545, '10.131.162.80', options, (err) => {
if(err){
msg.payload = "Error on client creation: "+err;
node.send(err);
}
});
global.set('dummyToolClient', op);
op.on('error',(err)=>{
msg.payload = err.toString();
node.send(msg);
})
op.on('connect',(data)=>{
msg.payload = data;
node.send(msg);
})
op.on("close",(data)=>{
msg.payload = data.toString();
node.send(msg);
})
}
catch(error){
msg.payload = error.toString();
node.send(msg);
}return msg;



Regards
Vinoth

**Comment by AbhayKariya** [comment]
Did anyone try with the desoutter Open protocol Simulator?
