### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by machadotiago** [netsmarttech/node-open-protocol#6]
When using "custom MID" and selecting MID 80 with Power Focus 6000, NR gives an uncaught exception:

![capture_2](https://user-images.githubusercontent.com/3775353/52149503-0be24f80-2654-11e9-9863-1ba30131c707.PNG)

Apparently it's crashing during the parsing process of the received message.

**Comment by gfcittolin** [comment]
Issue fixed on #7
